wearthe_wearthe_api_test_page:
    path:     /
    defaults:
        _controller: WeartheWeartheBundle:Default:index

wearthe_wearthe_internal_api:
    path:     /api/{locationType}/{location}/{gender}/{formality}/
    defaults: { _controller: WeartheWeartheBundle:Api:main }
    requirements:
        locationType:   1|2
